### ISSUE TITLE
zipbomb can break the consumer

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-core-messaging#11]
If you feed a malformed archive with a zipbomb inside to the Consumer it will try to unpack it which can cause OOM. I have a reproducer that broke our archive handler which based on insights-core-messaging.

**Comment by csams** [comment]
We can't consistently tell the true size of an archive before decompression, so we just attempt it and allow you to configure a timeout with the `extract_timeout` keyword in the `service` config. You'll need `coreutils` installed so the `timeout` command is available.

**Comment by quarckster** [comment]
thank you @csams for the response.
